name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Dockerfile
        run: |
          curl -o Dockerfile https://huggingface.co/spaces/draculaZxy/xyzdrac/blob/main/Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Push Docker image (Optional)
        run: echo "Image built successfully!"
